# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Better Scientific Software Tutorial
author: IDEAS Productivity Project
email: IdeasProductivity@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tutorial materials focusing on developer productivity, software sustainability,
  and reproducibility in scientific research software, particularly targeting 
  high-performance computers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bssw-tutorial.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# This is not a normal Jekyll thing, but sometimes it is useful to reference the
# production site URL even when we're serving locally for development purposes.
# So prod_url should be set to the same thing as url.
prod_url: "https://bssw-tutorial.github.io"
markdown: kramdown
#twitter_username: jekyllrb
github_username:  bssw-tutorial
rss: rss

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-last-modified-at
  - jekyll-pluralize
  - jekyll-github-metadata
  - jekyll-redirect-from
#  - flexible_include # We do use this, but it is not a gem

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

header_pages:
  - 
# none

# Default to simple ISO date without time.
# Note that this default does *not* affect the page.last-modified-at version.  
# That still needs to be passed to the `date` filter for formatting.
last-modified-at:
    date-format: '%F'

# For github-metadata
repository: bssw-tutorial/bssw-tutorial.github.io

# By convention, we "operate" on US Eastern time
timezone: America/New_York

google_analytics: UA-133695134-2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - reference-files/
  - README.md

# This is needed to generate output for future webinars
future: true

collections:
  people:
    output: true

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"

# Useful for debugging and quality assurance
# Note: setting strict_variables turns out not to be so useful
# because use of undefined variables is common (i.e., checking
# to see if they've been defined)
liquid:
  error_mode: strict
  strict_filters: true

# Base URLs
doi-resolver-url: https://doi.org
github-url: https://github.com

# Base URLs for watching and embedding YouTube videos
youtube-watch-url: https://www.youtube.com/watch?v=
youtube-embed-url: https://www.youtube.com/embed/

# GH repository base URLs for tutorial development repos
ghr-presentations: https://github.com/bssw-tutorial/presentations
ghr-management: https://github.com/bssw-tutorial/tutorial-management
ghr-handson: https://github.com/bssw-tutorial/hello-numerical-world

# IDEAS Productivity project website URL
ideas-url: https://ideas-productivity.org