name: Check PR URLs

on: [pull_request, workflow_dispatch]

jobs:  
  urlchecks:
    name: check-urls
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - run: |
        echo Added and modified file list: \`${{ steps.files.outputs.added_modified }}\'

    # Run URL checks
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.0.26
      with:
        # only include the changed files
        include_files: ${{ steps.files.outputs.added_modified }}
        print_all: true
