name: Check All URLs

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # We maintain the list of the URLs excluded from checking in a separate file so that we can use
    # it in multiple workflows, while easily maintaining consistency.
    - name: Read exclude-urls list
      id: exclude
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/workflows/exclude-urls.txt

    # Several workflows are using urlchecker-action, so we have refactored common configuration
    # elements into a separate file to simplify maintenance.
    - name: Read urlchecker common configuration
      id: config
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/workflows/urlchecker-config.txt
    - name: Echo urlchecker common configuration
      run: echo "${{ steps.config.outputs.content }}"


    - name: urls-checker
      uses: urlstechie/urlchecker-action@0.0.27
      with:
        # Use common configuration read in above
        ${{ steps.config.outputs.content }}
