name: Check All URLs

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read exclude-urls list
      id: exclude
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/workflows/exclude-urls.txt
    - name: Echo exclude-urls
      run: echo "${{ steps.exclude.outputs.content }}"

    - name: urls-checker
      uses: urlstechie/urlchecker-action@0.0.27
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md

        # Need to exclude a few things
        # https://en.w is an incomplete snippet of output in handson-m03-git-workflows.md
        # https://github.com/bssw-tutorial/presentations/blob/master is asigned to a variable used to build complete URLs in utilities.md
        # https://doi.org/10.1126/science.aah6168 is a resource which consistently fails, probably due to response time.  As a DOI, it should be quite reliable.
        # https://doi.org/10.1002/spe.2220 is a resource which consistently fails, probably due to response time.  As a DOI, it should be quite reliable
        exclude_urls: https://en.w,https://github.com/bssw-tutorial/presentations/blob/master,https://doi.org/10.1126/science.aah6168,https://doi.org/10.1002/spe.2220
        
        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # The timeout seconds to provide to requests, defaults to 5 seconds
        timeout: 5

        # How many times to retry a failed request (each is logged, defaults to 1)
        retry_count: 3

        # choose if the force pass or not
        #force_pass : true
