name: Check PR URLs

on: [pull_request, workflow_dispatch]

jobs:  
  urlchecks:
    name: check-urls
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    
    - name: pr-files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - run: |
        echo Added and modified file list: \`${{ steps.pr-files.outputs.added_modified }}\'

#    # Run URL checks
#    - name: URLs-checker
#      uses: urlstechie/urlchecker-action@0.0.26
#      with:
#        save: "urls.csv"
#        # only include the changed files
#        include_files: ${{ steps.pr-files.outputs.added_modified }}
#        print_all: true
#        
#    # In case of failure, upload results as artifacts
#    - name: Archive URL checking results
#      if: failure()
#      uses: actions/upload-artifact@v2-preview
#      with:
#        name: urlchecker-results
#        path: urls.csv
