name: Check All URLs

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # We maintain the list of the URLs excluded from checking in a separate file so that we can use
    # it in multiple workflows, while easily maintaining consistency.
    - name: Read exclude-urls list
      id: exclude
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/workflows/exclude-urls.txt

    - name: urls-checker
      uses: urlstechie/urlchecker-action@0.0.27
      with:
        # Use common exclude list read in above
        ${{ steps.exclude.outputs.content }}
        timeout: 10
        retry_count: 3
        print_all: false
