name: Check PR URLs

on: [pull_request, workflow_dispatch]

jobs:  
  urlchecks:
    name: check-urls
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'

    # Run URL checks
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.0.26
      with:
        # only include the changed files
        include_files: ${{ steps.files.outputs.added_modified }}
        file_types: .md,.html
        exclude_urls: https://en.w,https://github.com/bssw-tutorial/presentations/blob/master,https://doi.org/10.1126/science.aah6168,https://doi.org/10.1002/spe.2220
        print_all: false
