name: Check PR URLs

on: [pull_request, workflow_dispatch]

jobs:  
  urlchecks:
    name: check-urls
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    
    - name: pr-files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - run: |
        mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
        for added_modified_file in "${added_modified_files[@]}"; do
          echo "Do something with this ${added_modified_file}."
        done
          
#    # Run URL checks
#    - name: URLs-checker
#      uses: urlstechie/urlchecker-action@0.0.26
#      with:
#        save: "urls.csv"
#        # only include the changed files
#        include_files: ${{ steps.files.outputs.added_modified }}
#        print_all: true
#        
#    # In case of failure, upload results as artifacts
#    - name: Archive URL checking results
#      if: failure()
#      uses: actions/upload-artifact@v2-preview
#      with:
#        name: urlchecker-results
#        path: urls.csv
