name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

# GH_TOKEN must be an organization-level secret
env:
  MY_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  assign_to_board:
    runs-on: ubuntu-latest
    name: Assign to organization board
    steps:
    - name: Assign ISSUES to the organization-level board
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/orgs/bssw-tutorial/projects/1'
        column_name: 'Backlog'
